#!/usr/bin/env python3

import argparse

import submodule
import patch

parser = argparse.ArgumentParser(prog="dcr")

subparsers = parser.add_subparsers(title="subcommand",
     help="subcommands that dcr support.",
     dest="subcommand")

submodule.register_module_args(subparsers)
patch.register_module_args(subparsers)

args = parser.parse_args()

submodule.run_with_module_args(args)
patch.run_with_module_args(args)