#!/usr/bin/env python3

'''
dcr tool to manipulate deepin-code-release.
'''

import argparse

import submodule
import patch

PARSER = argparse.ArgumentParser(prog="dcr")

SUBPARSER = PARSER.add_subparsers(title="subcommand",
                                  help="subcommands that dcr support.",
                                  dest="subcommand")

submodule.register_module_args(SUBPARSER)
patch.register_module_args(SUBPARSER)

ARGS = PARSER.parse_args()

submodule.run_with_module_args(ARGS)
patch.run_with_module_args(ARGS)
